### PR TITLE
Update to latest zig

### PR DESCRIPTION
**Pull request by Avokadoen**

### CODE REVIEW

**Comment by SpexGuy** [comment]
Thanks, this looks great! I'm ready to merge it once it's no longer marked as a draft.

**Comment by Avokadoen** [comment]
Great, not completly done yet, but will mark it as PR soon (tm) 😅

**Comment by Avokadoen** [comment]
> Why expose this? Seems like just an extra unnecessary step for users.

Hi I am still stuck on some errors. This change was done because I was not able to use any functions with usingnamespace (maybe related to the namespace change in 0.9?). I agree its a negative change 😄 

The final blocking issue is that ``@import("build_options")`` cause unable to find error. Not sure what is wrong at this point. @SpexGuy do you have any idea?

**Comment by Avokadoen** [comment]
Maybe a Zig bug? Looking at [0.9 release notes](https://ziglang.org/download/0.9.0/release-notes.html#Build-Options) it seems like usage is valid here, or maybe they have change the API in master

**Comment by Avokadoen** [comment]
The issue was I tried to import tracy.zig by using addPackage instead of moving the file causing the exe step to not share the configuration with the tracy.zig file/package.

**Comment by Avokadoen** [comment]
Ok should be green to go. Not sure your preferred git history here since currently only the latest commit will compile so it might be an idea to simply squash all commits into one and use message "update to latest zig" or something :)

**Comment by Avokadoen** [comment]
@SpexGuy Give me a heads up if there are any issues with the current PR I'll try to get to them ASAP 👍

**Comment by SpexGuy** [comment]
Thanks, looks good!

**Pull request merged**
